### ISSUE TITLE
How to get buffer of dots

### ISSUE THREAD

**Issue by codergautam** [aarnas/image-in-image#4]
I want to get buffer of dots of the screen, to check if there is a specific object in my screen. 

using this lib to capture:  https://github.com/Krombik/keysender#capture

```
const hwnd = new Hardware(null);
const bufferImageData1 = hwnd.workwindow.capture({ x: 0, y: 0, width: 500, height: 500 });
console.log(bufferImageData1);
const bufferImageData2 = hwnd.workwindow.capture({ x: 0, y: 0, width: 25, height: 25 });
console.log(bufferImageData2);

So Im using this modules capture https://github.com/Krombik/keysender#capture function and this modules https://www.npmjs.com/package/image-in-image/v/1.0.2 image-in-image detector.

const main = async () => {
  const test2 = await findImage(
    bufferImageData1,
    bufferImageData2,
    "image/png",
    "image/png",
    1 // optional aspect ratio, default 1
  );
  console.log(test2);
};

main();
```

I'm trying to capture my desktop and use the returned Buffer with pixels in both the bufferImageData1 and the bufferImageData2 variable (This is just for testing but its not working). Maybe i'm putting the wrong format in the findImage function? Idk. Any help? 

I am getting this error

{
  error: 500,
  message: 'Something went wrong, might be that images path not right'
}

**Comment by aarnas** [comment]
I have used similar functionality in my other project, you can have a look using robotjs https://github.com/aarnas/more-than-clicker/blob/main/automation-back/src/utils/findImage.ts
